#!/sbin/sh

# fixing CPU clocks to avoid issues in recovery
echo 1024000 > /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq
echo 245760 > /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq


# trigger blue LED
echo '255' > /sys/class/leds/blue/brightness
# trigger button-backlight
echo '255' > /sys/class/leds/button-backlight/brightness
# trigger short vibration
echo "100" > /sys/class/timed_output/vibrator/enable

cat /dev/input/event1 > /dev/keycheck&
sleep 3

# trigger blue LED
echo '0' > /sys/class/leds/blue/brightness
# trigger button-backlight
echo '0' > /sys/class/leds/button-backlight/brightness


kill -9 $!

if [ -s /dev/keycheck -o -e /cache/recovery/boot ]
then
  stop adbd

  # correct LCD-backlight brightness
  echo '255' > /sys/class/leds/lcd-backlight/brightness

	rm /cache/recovery/boot
	mount -o remount,rw rootfs /
	umount -l /system
	umount -l /data
	umount -l /cache
	umount -l /sdcard
	umount -l /mnt/sdcard
	rm -r /sdcard
	rm -r /not/sdcard
	mkdir /sdcard
	mkdir /tmp
	rm /etc
	mkdir /etc
	cp /recovery.fstab /etc/recovery.fstab
	mount /dev/block/mmcblk0p1 /sdcard
	mount /dev/block/mtdblock0 /system

  PID_SUFFIX_PROP=$(/system/bin/getprop ro.usb.pid_suffix)	
	echo 0 > /sys/class/android_usb/android0/enable
  echo 0fce > /sys/class/android_usb/android0/idVendor
  # 6156 = haida , prefix is 6 = mass_storage,adb
  echo 6${PID_SUFFIX_PROP} > /sys/class/android_usb/android0/idProduct
  echo "mass_storage,adb" > /sys/class/android_usb/android0/functions
  echo 1 > /sys/class/android_usb/android0/enable
	# /system/bin/setprop sys.usb.state ${USB_CONFIG_PROP}

	umount -l /system

	/sbin/recovery &
	/sbin/adbd_rec recovery
fi

#continue booting

